version: '3.8'

services:
  clinic-app:
    build: .
    container_name: clinic-management-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      # Persistent data directories (survive Docker uninstall/reinstall)
      - ${CLINIC_DATA_ROOT}/database:/app/data
      - ${CLINIC_DATA_ROOT}/config:/app/config
      - ${CLINIC_DATA_ROOT}/uploads:/app/uploads
      - ${CLINIC_DATA_ROOT}/logs:/app/logs
      - ${CLINIC_DATA_ROOT}/backups:/app/backups
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/clinic.db
      - PORT=3000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - clinic-network

  nginx:
    image: nginx:alpine
    container_name: clinic-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ${CLINIC_DATA_ROOT}/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CLINIC_DATA_ROOT}/logs:/var/log/nginx
    depends_on:
      - clinic-app
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge